### ISSUE TITLE
压缩推流，然后播放出错

### ISSUE THREAD

**Issue by gp888** [javandoc/MediaPlus#7]
我的视频采集不是用的安卓相机，是usb外接摄像头，然后回调的nv21的数据帧，转i420格式，之后就用的你的LiveMediaManager.EncodeH264压缩，推流后，拉下来的是
![Screenshot_20190630_132857_com huawei himovie](https://user-images.githubusercontent.com/16898209/60392722-968e8400-9af8-11e9-904e-2553a28e9f5e.jpg)

所以我想问问，这个压缩能配置参数吗？
我视频帧数据是1280*720的

**Comment by javandcpp** [comment]
LibJniVideoProcess.NV21TOI420(mVideoSizeConfig.srcFrameWidth, mVideoSizeConfig.srcFrameHeight, m_nv21Data, m_I420Data);    
把m_I420Data写入本地看下YUV数据播放是否正常
